export enum TypeIncident {
  DIVERGENCE_GRE_A_GRE = 'DIVERGENCE_GRE_A_GRE',
  DIVERGENCE_EVALUATION = 'DIVERGENCE_EVALUATION',
  ANOMALIE_SOUMISSION = 'ANOMALIE_SOUMISSION',
  ERREUR_IA = 'ERREUR_IA',
  CONFIANCE_FAIBLE = 'CONFIANCE_FAIBLE',
}
